#!/bin/bash
set -e

# Get the current directory
PARAMETER_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Get the parent directory which should be the main directory of ProteoSeeker.
# Overwrite the following value if you need to set another path for the main directory of ProteoSeeker.
PS_PATH=$(dirname "${PARAMETER_DIR}")

# Overwrite the following value if you need to set another path for the directory that will contain all the results generated by the tests.
# The directory set in the parameter files used to run the tests by ProteoSeeker will contain only the resultss associated with the taxonomy analysis.
# Be cautioned that the results from any of the samples may add up to hundreds of GB. Specifically the taxonomy results, meaning those retained in
# the directory set in the parameter files take very little space in memory. The rest of the results take the most memory space.
RESULTS_ALL_PATH="${PS_PATH}/Benchmark"

# Paths for the Kraken2 and protein databases
KRAKEN_8_DB_PATH="/mnt/4529bb0c-30cc-4e67-8f04-e94a1b226730/Works/Enzymes_Metagenomes/ps_tools/kraken2/kraken2_databases/kraken2_8st_db"
KRAKEN_16_DB_PATH="/mnt/4529bb0c-30cc-4e67-8f04-e94a1b226730/Works/Enzymes_Metagenomes/ps_tools/kraken2/kraken2_databases/kraken2_db_16"
KRAKEN_72_DB_PATH="/mnt/4529bb0c-30cc-4e67-8f04-e94a1b226730/Works/Enzymes_Metagenomes/ps_tools/kraken2/kraken2_databases/kraken2_db_72"
PROTEIN_DB_PATH="/mnt/4529bb0c-30cc-4e67-8f04-e94a1b226730/Works/Enzymes_Metagenomes/parameter_files/docker/nr_part.fasta"

# Create the directory for the main part of the results, if not created already.
if [ ! -d "${RESULTS_ALL_PATH}" ]; then
    mkdir "${RESULTS_ALL_PATH}"
fi
