#!/bin/bash
set -e

# Get the current directory
INSTALLATION_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# Get the parent directory which should be the main directory of ProteoSeeker.
PS_DIR=$(dirname "${INSTALLATION_DIR}")
# The name of the parameter file.
PARAMETER_FILE="${PS_DIR}/par_tax_k_p.txt"

# Sourcing
source "${INSTALLATION_DIR}/find_conda.sh"
source "${INSTALLATION_DIR}/find_mb_cb.sh"
source "${INSTALLATION_DIR}/find_pd.sh"

# Phylo - Kraken - Paired
# Creating the file for the input paths and option and writing in it.
echo "#---------Input and output options---------" > "${PARAMETER_FILE}"
echo "input_folder=\"input\"" >> "${PARAMETER_FILE}"
echo "sra_code=\"SRR12829170\"" >> "${PARAMETER_FILE}"
echo "contigs=\"\"" >> "${PARAMETER_FILE}"
echo "protein_input=\"\"" >> "${PARAMETER_FILE}"
echo "adapters_path=\"${PS_DIR}/adapters.fa\"" >> "${PARAMETER_FILE}"
echo "protein_db_path=\"${PD_PATH}\"" >> "${PARAMETER_FILE}"
echo "kraken_db_path=\"${PS_DIR}/ps_tools/kraken2/kraken_databases/kraken2_8st_db\"" >> "${PARAMETER_FILE}"
echo "profiles_path=\"\"" >> "${PARAMETER_FILE}"
echo "profiles_phylo_path=\"\"" >> "${PARAMETER_FILE}"
echo "profiles_broad_path=\"${PS_DIR}/pfam_database/Pfam-A.hmm\"" >> "${PARAMETER_FILE}"
echo "swissprot_path=\"${PS_DIR}/swissprot_dtb/swissprot\"" >> "${PARAMETER_FILE}"
echo "motifs_path=\"${PS_DIR}/motifs.txt\"" >> "${PARAMETER_FILE}"
echo "output_path=\"${PS_DIR}/results/SRR12829170_tax_k_p\"" >> "${PARAMETER_FILE}"
echo "" >> "${PARAMETER_FILE}"

echo "#---------Protein family options---------" >> "${PARAMETER_FILE}"
echo "family_code=\"\"" >> "${PARAMETER_FILE}"
echo "family_code_phylo=\"\"" >> "${PARAMETER_FILE}"
echo "db_name=\"\"" >> "${PARAMETER_FILE}"
echo "db_name_phylo=\"\"" >> "${PARAMETER_FILE}"
echo "input_protein_names_status=\"\"" >> "${PARAMETER_FILE}"
echo "input_protein_names=\"\"" >> "${PARAMETER_FILE}"
echo "input_protein_names_phylo_status=\"\"" >> "${PARAMETER_FILE}"
echo "input_protein_names_phylo=\"\"" >> "${PARAMETER_FILE}"
echo "name_threshold=\"\"" >> "${PARAMETER_FILE}"
echo "" >> "${PARAMETER_FILE}"

echo "#---------General options---------" >> "${PARAMETER_FILE}"
echo "#---Pipeline---" >> "${PARAMETER_FILE}"
echo "seek_route=\"\"" >> "${PARAMETER_FILE}"
echo "paired_end=\"\"" >> "${PARAMETER_FILE}"
echo "compressed=\"\"" >> "${PARAMETER_FILE}"
echo "create_nr_db_status=\"\"" >> "${PARAMETER_FILE}"
echo "prefetch_size=\"\"" >> "${PARAMETER_FILE}"
echo "adapters_status=\"\"" >> "${PARAMETER_FILE}"
echo "add_seek_info=\"\"" >> "${PARAMETER_FILE}"
echo "add_taxonomy_info=\"\"" >> "${PARAMETER_FILE}"
echo "#---FastQC---" >> "${PARAMETER_FILE}"
echo "skip_fastqc=\"\"" >> "${PARAMETER_FILE}"
echo "#---BBDuk---" >> "${PARAMETER_FILE}"
echo "bbduk_max_ram=\"\"" >> "${PARAMETER_FILE}"
echo "clear_space=\"\"" >> "${PARAMETER_FILE}"
echo "#---Megahit---" >> "${PARAMETER_FILE}"
echo "k_list=\"\"" >> "${PARAMETER_FILE}"
echo "#---Kraken---" >> "${PARAMETER_FILE}"
echo "kraken_mode=\"\"" >> "${PARAMETER_FILE}"
echo "kraken_threshold=\"\"" >> "${PARAMETER_FILE}"
echo "kraken_memory_mapping=\"\"" >> "${PARAMETER_FILE}"
echo "#---Binning---" >> "${PARAMETER_FILE}"
echo "binning_tool=\"\"" >> "${PARAMETER_FILE}"
echo "binning_max_ram=\"\"" >> "${PARAMETER_FILE}"
echo "bin_contig_len=\"1000\"" >> "${PARAMETER_FILE}"
echo "bin_kmer=\"\"" >> "${PARAMETER_FILE}"
echo "comebin_batch_size=\"\"" >> "${PARAMETER_FILE}"
echo "#---CD-HIT---" >> "${PARAMETER_FILE}"
echo "cd_hit_t=\"\"" >> "${PARAMETER_FILE}"
echo "cd_hit_max_mem=\"\"" >> "${PARAMETER_FILE}"
echo "#---Gene prediction---" >> "${PARAMETER_FILE}"
echo "gene_encoding=\"\"" >> "${PARAMETER_FILE}"
echo "genetic_code=\"\"" >> "${PARAMETER_FILE}"
echo "#---HMMER---" >> "${PARAMETER_FILE}"
echo "val_type=\"\"" >> "${PARAMETER_FILE}"
echo "second_dom_search=\"\"" >> "${PARAMETER_FILE}"
echo "e_value_nodom_thr=\"\"" >> "${PARAMETER_FILE}"
echo "#---Annotation---" >> "${PARAMETER_FILE}"
echo "add_type=\"organism bias  number of organisms biosample name\"" >> "${PARAMETER_FILE}"
echo "add_info=\"synthetic metagenome no  10  SAMN16441671\"" >> "${PARAMETER_FILE}"
echo "#---Threads---" >> "${PARAMETER_FILE}"
echo "thread_num=\"4\"" >> "${PARAMETER_FILE}"
echo "filtering_threads=\"\"" >> "${PARAMETER_FILE}"
echo "" >> "${PARAMETER_FILE}"

echo "#---------Processes performed after---------" >> "${PARAMETER_FILE}"
echo "after_preprocessing=\"\"" >> "${PARAMETER_FILE}"
echo "after_assembly=\"\"" >> "${PARAMETER_FILE}"
echo "after_gene_pred=\"\"" >> "${PARAMETER_FILE}"
echo "after_binning=\"\"" >> "${PARAMETER_FILE}"
echo "after_db=\"\"" >> "${PARAMETER_FILE}"
echo "after_tm=\"\"" >> "${PARAMETER_FILE}"
echo "after_ap=\"\"" >> "${PARAMETER_FILE}"
echo "" >> "${PARAMETER_FILE}"

echo "#---------Processes performed up to---------" >> "${PARAMETER_FILE}"
echo "up_to_sra=\"\"" >> "${PARAMETER_FILE}"
echo "up_to_databases=\"\"" >> "${PARAMETER_FILE}"
echo "up_to_preprocessing_com=\"\"" >> "${PARAMETER_FILE}"
echo "up_to_preprocessing_uncom=\"\"" >> "${PARAMETER_FILE}"
echo "up_to_alignment=\"\"" >> "${PARAMETER_FILE}"
echo "" >> "${PARAMETER_FILE}"

echo "#---------Tool enviroments---------" >> "${PARAMETER_FILE}"
echo "sra_env=\"\"" >> "${PARAMETER_FILE}"
echo "fastqc_env=\"\"" >> "${PARAMETER_FILE}"
echo "bbduk_env=\"\"" >> "${PARAMETER_FILE}"
echo "megahit_env=\"\"" >> "${PARAMETER_FILE}"
echo "kraken_env=\"\"" >> "${PARAMETER_FILE}"
echo "metabinner_env=\"\"" >> "${PARAMETER_FILE}"
echo "comebin_env=\"\"" >> "${PARAMETER_FILE}"
echo "cdhit_env=\"\"" >> "${PARAMETER_FILE}"
echo "genepred_env=\"\"" >> "${PARAMETER_FILE}"
echo "hmmer_env=\"\"" >> "${PARAMETER_FILE}"
echo "diamond_env=\"\"" >> "${PARAMETER_FILE}"
echo "taxonkit_env=\"\"" >> "${PARAMETER_FILE}"
echo "phobius_env=\"\"" >> "${PARAMETER_FILE}"
echo "bowtie_env=\"\"" >> "${PARAMETER_FILE}"
echo "" >> "${PARAMETER_FILE}"

echo "#---------Tool paths---------" >> "${PARAMETER_FILE}"
echo "conda_bin=\"${CONDA_INST_DIR}\"" >> "${PARAMETER_FILE}"
echo "conda_sh=\"${CONDA_SH_PATH}\"" >> "${PARAMETER_FILE}"
echo "prefetch_path=\"\"" >> "${PARAMETER_FILE}"
echo "vdb_validate_path=\"\"" >> "${PARAMETER_FILE}"
echo "fastq_dump_path=\"\"" >> "${PARAMETER_FILE}"
echo "fastqc_path=\"\"" >> "${PARAMETER_FILE}"
echo "gzip_path=\"\"" >> "${PARAMETER_FILE}"
echo "cat_path=\"\"" >> "${PARAMETER_FILE}"
echo "bbduk_path=\"\"" >> "${PARAMETER_FILE}"
echo "megahit_path=\"\"" >> "${PARAMETER_FILE}"
echo "kraken_path=\"\"" >> "${PARAMETER_FILE}"
echo "metabinner_bin_path=\"${MBINPATH}\"" >> "${PARAMETER_FILE}"
echo "comebin_bin_path=\"${CBINPATH}\"" >> "${PARAMETER_FILE}"
echo "cd_hit_path=\"\"" >> "${PARAMETER_FILE}"
echo "fraggenescanrs_path=\"${PS_DIR}/ps_tools/fgsrs/FragGeneScanRs\"" >> "${PARAMETER_FILE}"
echo "hmmscan_path=\""\" >> "${PARAMETER_FILE}"
echo "hmmpress_path=\"\"" >> "${PARAMETER_FILE}"
echo "hmmfetch_path=\"\"" >> "${PARAMETER_FILE}"
echo "diamond_path=\"\"" >> "${PARAMETER_FILE}"
echo "taxonkit_path=\"\"" >> "${PARAMETER_FILE}"
echo "phobius_path=\"\"" >> "${PARAMETER_FILE}"
echo "bowtie_build_path=\"\"" >> "${PARAMETER_FILE}"
echo "bowtie_path=\"\"" >> "${PARAMETER_FILE}"
echo "" >> "${PARAMETER_FILE}"